version: "3.1"
services:
  nginx:
    image: 453510142829.dkr.ecr.eu-west-1.amazonaws.com/padelrackets-docker-nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
  app:
    restart: always
    build:
      context: .
    image: 453510142829.dkr.ecr.eu-west-1.amazonaws.com/padelrackets-docker-app
    expose:
      - "8080"